title: Action Congress
author: Lauren Dennedy
email: lauren@actioncongress.org
description: > # this means to ignore newlines until "baseurl:"
  Home page of the Action Congress Organization.

github_username:  actioncongress

sass:
    style: compressed
